### PR TITLE
Handle non-ASCII URLs & Minor improvements on image filenames

### PR DESCRIPTION
**Pull request by sanghoon**
Changes

- Generate a filename when a basename is an empty string
  - The basename of `path` of an URL can be an empty string (e.g. `http://sample.domain/abcd/?query` => path is `abcd/` and basename is an empty string).
  - In such cases, the downloader generates a filename with the md5 hash value of a full URL.

- Generate a file extension from the image content
  - Instead of using the last dot-separated part (which may contain an arbitrary string ) or a default value (`.gif`), the downloader infers a file extension from the image content.

- Handle non-ASCII URLs
  - Implemented a naive URL encoding function so that the downloader can download from URLs with non-ASCII characters.

### CODE REVIEW

**Comment by ostrolucky** [comment]
Do you have an example for non-ascii image url? I didn't realize urllib.request.Request() cannot handle those?

**Comment by sanghoon** [comment]
Here is an example.
```
In [25]: def try_fetch(url):
    ...:     try:
    ...:         req = urllib.request.Request(url)
    ...:         html = urllib.request.urlopen(req).read()
    ...:         print(f"HTML size: {len(html)}")
    ...:     except Exception as e:
    ...:         print(f"Error occured: ({type(e)}) {e}")
    ...:

In [30]: try_fetch("https://google.com/a_non_existing_path")
Error occured: (<class 'urllib.error.HTTPError'>) HTTP Error 404: Not Found

In [31]: try_fetch("https://google.com/한국어")
Error occured: (<class 'UnicodeEncodeError'>) 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)

In [32]: try_fetch("https://google.com/?test_query=ascii")
HTML size: 15069

In [33]: try_fetch("https://google.com/?test_query=한국어")
Error occured: (<class 'UnicodeEncodeError'>) 'ascii' codec can't encode characters in position 17-19: ordinal not in range(128)
```

FYI, it seems that the error occurs at urlopen(), not Request()

```
In [36]: req = urllib.request.Request("https://google.com/?test_query=한국어")

In [37]: html = urllib.request.urlopen(req).read()

UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-19: ordinal not in range(128)
```

**Comment by ostrolucky** [comment]
This seem better way to around this:
```python
import urllib.parse
import string
import urllib.request

req = urllib.request.Request(urllib.parse.quote("https://google.com/?test_query=한국어", safe=string.printable))
print(urllib.request.urlopen(req).read())
```

**Comment by sanghoon** [comment]
It seemed that the standards require us to use different encoding schemes on a path part and a query part.

https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote
> **urllib.parse.quote(string, safe='/', encoding=None, errors=None)**
> ... By default, this function is intended for quoting the path section of a URL.

https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus
> **urllib.parse.quote_plus(string, safe='', encoding=None, errors=None)**
> Like quote(), but also replace spaces with plus signs, as required for quoting HTML form values when building up a query string to go into a URL.

Since I'm not an expert on Web standards,
I'm not sure whether it's okay to use quote() for the whole URL or if it's better to encode the path and query separately.

-----

Furthermore, your suggestion can't handle URLs with spaces
Will these spaces be handled w/ urlopen()?
```
In [13]: sample_url = "https://google.com/a path with spaces/한국어/?q1=query with spaces&q2=한국어"

In [14]: req = urllib.request.Request(urllib.parse.quote(sample_url, safe=string.printable))
In [17]: req.get_full_url()
Out[17]: 'https://google.com/a path with spaces/%ED%95%9C%EA%B5%AD%EC%96%B4/?q1=query with spaces&q2=%ED%95%9C%EA%B5%AD%EC%96%B4'

In [19]: _encode_url(sample_url)  # The proposed impl.
Out[19]: 'https://google.com/a%20path%20with%20spaces/%ED%95%9C%EA%B5%AD%EC%96%B4/?q1%3Dquery+with+spaces%26q2%3D%ED%95%9C%EA%B5%AD%EC%96%B4'

```

-----

If you're afraid of adding a custom function manipulating URLs,
using a third-party library (e.g. https://stackoverflow.com/a/40654295) might be a good option.

**Comment by ostrolucky** [comment]
Well before we didn't do any quoting and urls with spacing worked, right? So that shouldn't change.

Btw my suggestion came from https://blog.krybot.com/a?ID=00700-d7b835d4-2481-44c0-837f-e9819e16c658

I'll use the native solution for now and wait to see if anyone has issues.

**Comment by sanghoon** [comment]
As I implement and run a simple test script,
I've found out that any of the original implementation and parse.quote() can't handle an URL with spaces correctly.

Here is my test script
https://github.com/sanghoon/Bulk-Bing-Image-downloader/blob/temp/non-ascii-url/temp_url_test/simple_test.py

And the following are its results.

```
## URL: https://.../an_ordinary_path.txt
[ ] A plain URL
[ ] Simple quote()
[ ] An encoded URL

## URL: https://.../a path with spaces.txt
[X] A plain URL
    - URL can't contain control characters. '/sanghoon/Bulk-Bing-Image-downloader/temp/non-ascii-url/temp_url_test/a path with spaces.txt' (found at least ' ')
[X] Simple quote()
    - URL can't contain control characters. '/sanghoon/Bulk-Bing-Image-downloader/temp/non-ascii-url/temp_url_test/a path with spaces.txt' (found at least ' ')
[ ] An encoded URL

## URL: https://.../a_path_with_non_ascii_테스트.txt
[X] A plain URL
    - 'ascii' codec can't encode characters in position 96-98: ordinal not in range(128)
[ ] Simple quote()
[ ] An encoded URL

## URL: https://.../a path with spaces and non ascii 테스트.txt
[X] A plain URL
    - URL can't contain control characters. '/sanghoon/Bulk-Bing-Image-downloader/temp/non-ascii-url/temp_url_test/a path with spaces and non ascii 테스트.txt' (found at least ' ')
[X] Simple quote()
    - URL can't contain control characters. '/sanghoon/Bulk-Bing-Image-downloader/temp/non-ascii-url/temp_url_test/a path with spaces and non ascii %ED%85%8C%EC%8A%A4%ED%8A%B8.txt' (found at least ' ')
[ ] An encoded URL
```

**Comment by ostrolucky** [comment]
Thanks for digging deeper. Let's go with your implementation then. Too bad python is so bad with this, it should handle these things on its own! I've reverted my commit.

**Pull request merged**
